name: Push to Docker Hub - Frontend Server
on:
    push:
        branches:
            - deploy
env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPO_NAME: kavishkasula/frontend-server
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKER_USERNAME }}
                  password: ${{ env.DOCKER_PASSWORD }}
            - name: Build and push image
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: ${{ env.REPO_NAME }}
